package com.csc340.axolotl_crud_api.axolotl;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class AxolotlService {

  @Autowired
  private AxolotlRepository repository;

  // Get all animals
  public List<Axolotl> getAllAnimals() {
    return repository.findAll();
  }

  // Get one by id
  public Axolotl getAnimalById(long id) {
    return repository.findById(id).orElse(null);
  }

  // Search name contains
  public List<Axolotl> getByNameContains(String key) {
    return repository.searchByName(key);
  }

  // Get by category (morph)
  public List<Axolotl> getByCategory(String morph) {
    return repository.findByMorphIgnoreCase(morph);
  }

  // Add new
  public Axolotl addAnimal(Axolotl a) {
    // ID is autogenerated; just save
    return repository.save(a);
  }

  // Update existing
  public Axolotl updateAnimal(Long id, Axolotl updates) {
    Optional<Axolotl> currentOpt = repository.findById(id);
    if (currentOpt.isEmpty()) {
      return null; // or throw if you prefer
    }
    Axolotl current = currentOpt.get();
    // Copy over fields (simple style like the class demo)
    current.setName(updates.getName());
    current.setDescription(updates.getDescription());
    current.setMorph(updates.getMorph());
    current.setAge(updates.getAge());
    current.setActiveDate(updates.getActiveDate());
    return repository.save(current);
  }

  // Delete
  public void deleteAnimal(Long id) {
    repository.deleteById(id);
  }
}
